---
- name: Add Git repo to ArgoCD and create application
  hosts: argo_servers
  become: true
  gather_facts: yes

  vars:
    argocd_server: "argocd.example.com"  # Replace with actual ArgoCD server
    argocd_username: "admin"
    argocd_password: "your-password"     # Store this securely (e.g., in Ansible Vault)
    git_repo_url: "https://github.com/AdidelaHarishReddy/project_k8s_yaml.git"
    git_repo_name: "my_project_yaml_repo"
    app_name: "my-app"
    app_namespace: "project"
    app_path: "./"
    kube_dest_server: "https://kubernetes.default.svc"

  tasks:

    - name: Install ArgoCD CLI
      ansible.builtin.shell: |
        curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
        chmod +x /usr/local/bin/argocd
      args:
        creates: /usr/local/bin/argocd  # Don't re-download if already installed


    - name: getting the host name
      ansible.builtin.shell: |
        curl -s "https://checkip.amazonaws.com"
      register: hostname_master

    - name: getting the argocd nodeport
      ansible.builtin.shell: |
        kubectl get svc -n argocd | awk '{print $5}' | tail -2 | head -1 | grep -o '443:[0-9]*' | cut -d ':' -f2 
      register: nodeport
      environment:
         KUBECONFIG: /home/ubuntu/.kube/config

    - name: Debug nodeport
      ansible.builtin.debug:
        msg: "NodePort: {{ nodeport.stdout }}"

    - name: Debug nodeport
      ansible.builtin.debug:
        var: nodePort

    - name: getting argocd password
      ansible.builtin.shell: |
        kubectl get secrets -n argocd argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d | xargs -I{} echo "{}"
      register: password_raw
      environment:
         KUBECONFIG: /home/ubuntu/.kube/config

    - name: Login to ArgoCD
      ansible.builtin.shell: |
        argocd login "{{ hostname_master.stdout | trim }}:{{ nodeport.stdout | trim }}" --username {{ argocd_username }} --password {{ password_raw.stdout }} --insecure
      environment:
        ARGOCD_INSECURE: "true"  # Optional: avoid cert checks (not recommended for prod)

    - name: Add Git repository to ArgoCD
      ansible.builtin.shell: |
        argocd repo add {{ git_repo_url }} --name {{ git_repo_name }}
      register: repo_add_result
      failed_when: "'already exists' not in repo_add_result.stderr and repo_add_result.rc != 0"

    - name: Create Kubernetes namespace
      ansible.builtin.shell: |
        kubectl create namespace {{ app_namespace }}
      register: ns_result
      failed_when: "'already exists' not in ns_result.stderr and ns_result.rc != 0"
      environment:
         KUBECONFIG: /home/ubuntu/.kube/config


    - name: Create ArgoCD Application
      ansible.builtin.shell: |
        argocd app create {{ app_name }} \
          --repo {{ git_repo_url }} \
          --path {{ app_path }} \
          --dest-server {{ kube_dest_server }} \
          --dest-namespace {{ app_namespace }} \
          --project default \
          --sync-policy automated \
          --auto-prune \
          --self-heal
      register: app_create_result
      failed_when: "'already exists' not in app_create_result.stderr and app_create_result.rc != 0"

    - name: Sync ArgoCD Application (optional)
      ansible.builtin.shell: |
        argocd app sync {{ app_name }} --force

